### ISSUE TITLE
Module isn't working properly unless AudioFX is not disabled manually

### ISSUE THREAD

**Issue by kartun83** [therealahrion/JamesDSPManager#1]
I installed this module on latest RR 5.8.5, Xiaomi mi5s.
But until I manually disabled audiofx module doesn't work as expected and actually did nothing.
May be it would be convinient to include "pm disable org.cyanogenmod.audiofx" in installation script and enabling back on module deletion ?

**Comment by Zackptg5** [comment]
This is known with every audiomod (including v4a and dolby). Many users would prefer to just freeze or can get it to work depending on rom/device so we don't mess with it ourselves

**Comment by kartun83** [comment]
So, at least it worth to mention it in module setup log, to give first timers some idea how to setup it properly.
I'm not very familiar with this stuff yet, and installation instructions usually not clear or even absent.
