### ISSUE TITLE
Effect doesn't work properly untill UI is opened for first time

### ISSUE THREAD

**Issue by kartun83** [therealahrion/JamesDSPManager#2]
After reboot any music is distorted, until JamesDSP UI is opened for the first time. After that it sounds like it has to be.

**Comment by james34602** [comment]
If no other mods installed, it shouldn't distort any sound, because it haven't loaded into audio_server yet.
However, I recognise DSP effect module will not be registered until UI start up, I'm currently looking for solutions for this.

**Comment by kartun83** [comment]
Yes, it's the only mod installed. Thanks for your efforts.

**Comment by Zackptg5** [comment]
Just a note, v4a has the same issue. After booting, it's effects won't kick in until you toggle the master power switch

**Comment by james34602** [comment]
No stream exist, system should responsible to unregister the effect.
I think this mechanism isn't that bad.
If some high consumption audio effect enabled but doesn't turn off even no samples to process, it simply waste resources.

**Comment by Zackptg5** [comment]
Closed since this behavior won't be changed (it's the same with v4a anyways)
