### ISSUE TITLE
HQ/SQ install issues presisting

### ISSUE THREAD

**Issue by Stonebuilt** [therealahrion/JamesDSPManager#3]
install script still having problems detecting volume keys.

as per the dev post in XDA suggests, and as the install.sh says...
renamed _Ainur_JamesDSP-v1.5.1_(2-16-2018).zip_ to ...

Ainur_JamesDSP-v1.5.1-HQ(2-16-2018).zip 
Ainur_JamesDSP-v1.5.1_HQ.zip 
HQ_Hq_hq_Ainur_JamesDSP-v1.5.1_(2-16-2018).zip 
HQ.zip
(tried in uppercase, lowercase and also with SQ also)

all result in the request for volume up or down to continue.
happens with both magisk and twrp.

_installing on an oukitel k6000 pro, RR 5.8.3 Rom (Custom-not the lenovo port from needrom), SAURON MK II.I [update 26.02.2018], Magisk latest, busybox latest. etc etc._

if you need anything let me know if i can assist, this mod looks fantastic, thanks.

**Comment by Zackptg5** [comment]
I can't replicate your issue. I named it this: Ainur_JamesDSP-v1.5.1_HQ.zip and it worked as intended (tested in twrp). Can you make sure you didn't leave a space in the name and try it again? Then post a recovery.log, maybe it'll show something

**Comment by Stonebuilt** [comment]
i have no idea how or what i did wrong...

but it just installed fine via twrp with the name "Ainur_JamesDSP-v1.5.1_HQ.zip"

thanks!?
i think i need beer and a sanity check.

**Comment by Zackptg5** [comment]
Haha, no problem. I bet it was a space somewhere in the name, it's easy to miss
