### ISSUE TITLE
Not working on MIUi.?

### ISSUE THREAD

**Issue by DarkCoder0** [therealahrion/JamesDSPManager#4]
Hello. 
Is this jamesdsp not suppose to work on MIUi .. ?? I am currently using redmi Note 4x and stock MIUi 9.5. jamesdsp keeps closing instantly when I open it. So is this suppose to work only with other non modified custom roms. ??
If want any kind of log , let me know. 
Thanks..

**Comment by james34602** [comment]
I'm happy to see log.
I cannot guarantee it work for which ROM.

**Comment by Zackptg5** [comment]
This was fixed a while ago
